# NGROK PUBLIC URL FOR GRADING:
# https://24cac0c7bf81.ngrok-free.app
#
# This link exposes the Gitea UI running on port 3000 through ngrok.

# ngrok/up.yaml
---
- name: Expose Gitea with ngrok
  hosts: localhost
  connection: local
  tasks:
    - name: Authenticate ngrok with access token
      shell: ngrok config add-authtoken 30D2EM1UumnzuusGfpF6ft4Peje_4TLy8fdypJCgRN934xMst
      ignore_errors: true  # skip error if already authed

    - name: Start port-forwarding Gitea service on port 3000
      shell: nohup kubectl port-forward svc/gitea-http 3000:3000 > pf.log 2>&1 &
      async: 30
      poll: 0

    - name: Wait for port 3000 to become active
      wait_for:
        host: 127.0.0.1
        port: 3000
        timeout: 30

    - name: Launch ngrok tunnel for port 3000
      shell: nohup ngrok http 3000 > ngrok.log 2>&1 &
      async: 30
      poll: 0

    - name: Wait for ngrok to initialize
      pause:
        seconds: 5

    - name: Wait for ngrok tunnel to be available
      uri:
        url: http://127.0.0.1:4040/api/tunnels
        return_content: yes
      register: ngrok_response
      retries: 10
      delay: 3
      until: ngrok_response.status == 200

    - name: Display ngrok public URL
      debug:
        msg: "✅ Gitea is accessible at: {{ (ngrok_response.content | from_json).tunnels[0].public_url }}"
